export const GOOGLE_FONTS_URL = "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=Inter:wght@400;700&family=JetBrains+Mono:wght@400;700&display=swap";

export const TEMPLATES = {
  'apple-minimal': {
    bg: 'bg-white',
    text: 'text-gray-900',
    primary: 'text-black',
    buttonBg: 'bg-black hover:bg-gray-800',
    buttonText: 'text-white',
    font: 'font-inter',
    cardBg: 'bg-gray-50',
    borderColor: 'border-gray-200',
    overlayOpacity: 0.2,
  },
  'gold-luxury': {
    bg: 'bg-black',
    text: 'text-white',
    primary: 'text-yellow-400',
    buttonBg: 'bg-yellow-400 hover:bg-yellow-300',
    buttonText: 'text-black',
    font: 'font-playfair',
    cardBg: 'bg-gray-900',
    borderColor: 'border-yellow-400/30',
    overlayOpacity: 0.7,
  },
  'cyber-neon': {
    bg: 'bg-gray-900',
    text: 'text-cyan-300',
    primary: 'text-fuchsia-500',
    buttonBg: 'bg-fuchsia-500 hover:bg-fuchsia-400',
    buttonText: 'text-white',
    font: 'font-jetbrains',
    cardBg: 'bg-gray-800',
    borderColor: 'border-cyan-300/30',
    overlayOpacity: 0.8,
  },
  'bento-grid': {
    bg: 'bg-gray-100',
    text: 'text-gray-800',
    primary: 'text-indigo-600',
    buttonBg: 'bg-indigo-600 hover:bg-indigo-500',
    buttonText: 'text-white',
    font: 'font-inter',
    cardBg: 'bg-white',
    borderColor: 'border-gray-200',
    overlayOpacity: 0.3,
  },
  'dark-mode': {
    bg: 'bg-gray-900',
    text: 'text-white',
    primary: 'text-indigo-400',
    buttonBg: 'bg-indigo-600 hover:bg-indigo-500',
    buttonText: 'text-white',
    font: 'font-inter',
    cardBg: 'bg-gray-800',
    borderColor: 'border-indigo-400/30',
    overlayOpacity: 0.7,
  },
  'light-mode': {
    bg: 'bg-white',
    text: 'text-gray-900',
    primary: 'text-indigo-600',
    buttonBg: 'bg-indigo-600 hover:bg-indigo-500',
    buttonText: 'text-white',
    font: 'font-inter',
    cardBg: 'bg-gray-50',
    borderColor: 'border-gray-200',
    overlayOpacity: 0.2,
  },
  'forest-green': {
    bg: 'bg-green-900',
    text: 'text-white',
    primary: 'text-yellow-300',
    buttonBg: 'bg-yellow-300 hover:bg-yellow-200',
    buttonText: 'text-green-900',
    font: 'font-playfair',
    cardBg: 'bg-green-800',
    borderColor: 'border-yellow-300/30',
    overlayOpacity: 0.6,
  },
  'ocean-blue': {
    bg: 'bg-blue-900',
    text: 'text-white',
    primary: 'text-cyan-300',
    buttonBg: 'bg-cyan-300 hover:bg-cyan-200',
    buttonText: 'text-blue-900',
    font: 'font-inter',
    cardBg: 'bg-blue-800',
    borderColor: 'border-cyan-300/30',
    overlayOpacity: 0.7,
  },
  'sunset-orange': {
    bg: 'bg-orange-900',
    text: 'text-white',
    primary: 'text-yellow-300',
    buttonBg: 'bg-yellow-300 hover:bg-yellow-200',
    buttonText: 'text-orange-900',
    font: 'font-playfair',
    cardBg: 'bg-orange-800',
    borderColor: 'border-yellow-300/30',
    overlayOpacity: 0.6,
  },
  'royal-purple': {
    bg: 'bg-purple-900',
    text: 'text-white',
    primary: 'text-yellow-300',
    buttonBg: 'bg-yellow-300 hover:bg-yellow-200',
    buttonText: 'text-purple-900',
    font: 'font-inter',
    cardBg: 'bg-purple-800',
    borderColor: 'border-yellow-300/30',
    overlayOpacity: 0.7,
  },
};

export const EXCHANGE_RATE = 2800; // Taux de change USD vers CDF

export const DEFAULT_CREATOR_DATA = {
  labels: {},
  templateId: 'gold-luxury',
  googleFormUrl: '',
  layoutType: 'GALLERY',
  portfolioTitle: 'Mes Réalisations',
  sections: [],
};
